---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom
  namespace: kubedoom
  labels:
    app: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: kubedoom
        image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - containerPort: 5900
          protocol: TCP
